
# Cleaning Data ==================================================================================

# Files from 01_loading_data_and_cleaning_mapping_file.R
iris.RDS \
iris.set.RDS \
iris.ver.RDS \
iris.vir.RDS: 01_loading_and_cleaning_data.R iris.txt
	01_loading_and_cleaning_data.R


